config/routes.rb
Mysms::Application.routes.draw do

   resources :messages do
     collection do
       get 'sms_database'
       post 'add_receiver'
       get 'new_receiver'
     end
   end

  root :to => 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :name, :number
  validates_presence_of :name, :number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController


  def index
    @messages = Message.all
  end

  def create
    @message = Message.new(params[:message])
    if @message.save
      puts "---"*90
      # require 'nexmo'
      # nexmo = Nexmo::Client.new('c6ec048a', 'c86f0b89')
      # response = nexmo.send_message({:to => "#{@message.number}", :from => 'Decent Acad.', :text => 'Classes of 9th & 10th are starting under the fully attention of  Faisal Bhatti [software Eng @Devsinc(pvt Ltd), Principal ] and Dr Maimoona(KEMU).For Further details Contact at 03324167729. Decent Academy'})
      # puts response.inspect

      # require 'twilio-ruby'
      # account_sid = 'ACa31d8423032237dcfb631b4f6fc700e1'
      # auth_token = '9fcc1ee7920f62dd6d16bd746614fdb9'
      # @client = Twilio::REST::Client.new account_sid, auth_token
      # rsponse = @client.messages.create(
      #   from: '+14792085406',    #+18704667180
      #   to: '+923324167729',
      #   body: 'Classes of 9th & 10th are starting under the fully attention of  Faisal Bhatti [software Eng @Devsinc(pvt Ltd), Principal ] and Dr Maimoona(KEMU).For Further details Contact at 03324167729. Decent Academy'
      # )
      # puts rsponse.inspect


      require 'clockwork'
      api = Clockwork::API.new('26b9fa95254aa50ada2e514fbd324147e2c88f6a')
      message = api.messages.build( :to => '+923324167729', :from=>"Decent Acad", :content => 'Test Session of 9th & 10th are started. Contact at 03324167729. Decent Academy' )
      response = message.deliver
       
      if response.success
          puts response.message_id
      else
          puts response.error_code
          puts response.error_description
      end
    else
      puts "=="*90
    end
    flash[:message] = "Sms send to #{@message.name}"
    redirect_to root_path
    end

   def new
     @message = Message.new
   end

   def destroy
     @message = Message.find(params[:id])
     @message.destroy
     redirect_to root_path
   end
  def sms_database
    require 'nexmo'
    # key = c6ec048a
    #secret = c86f0b89
    nexmo = Nexmo::Client.new('0c6ad999', 'abdd4626')
      @messages = Message.all
      @messages.each do |message|
        response = nexmo.send_message({:to => "#{message.number}", :from => 'Decent Acad.', :text => 'Classes of 9th & 10th are starting under the fully attention of  Faisal Asghar Bhatti [software Eng @Devsinc(pvt Ltd), Principal ] and Dr Maimoona Asghar(KEMU).For Further details Contact at 03324167729. Decent Academy'})
      end
    flash[:message] = "Sms sent to all"
     redirect_to root_path
  end

  def add_receiver
    @message = Message.new(params[:message])
    if @message.save
      flash[:message] = "Successfully Added..."
      redirect_to root_path
    end
  end

  def new_receiver
    @message = Message.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, :url => url, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :number, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                messages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/messages/index.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h3><%= "Messages" %></h3>
  <div class="back-ground"><%= flash[:message] %></div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to message.id, message_path(message) %></td>
        <td><%= message.name %></td>
        <td><%= message.number %></td>
        <td><%=l message.created_at %></td>
        <td>
          <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_message_path(message), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      message_path(message),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Receiver', new_receiver_messages_path, :class => 'btn btn-primary' %>
<%= link_to 'Add & send sms', new_message_path, :class => 'btn btn-primary' %>
<%= link_to 'send sms to all', sms_database_messages_path,:class => 'btn btn-primary' %>

app/views/messages/new.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render 'form', :url => messages_path %>

app/views/messages/new_receiver.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%= "New Receiver" %></h1>
</div>
<%= render 'form' , :url => add_receiver_messages_path %>

app/views/messages/show.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @message.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @message.number %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              messages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_message_path(@message), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              message_path(@message),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>